server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://localhost/ogcapi
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: pygeoapi default instance
        description: pygeoapi provides an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

resources: {}
    # sergipe-lito:
    #     type: collection
    #     title: Populated Places
    #     description: Point symbols with name attributes. Includes all admin-0 capitals and some other major cities. We favor regional significance over population census in determining our selection of places. Use the scale rankings to filter the number of towns that appear on your map.
    #     keywords:
    #         - populated places
    #         - cities
    #         - towns
    #     links:
    #         - type: text/html
    #           rel: canonical
    #           title: information
    #           href: http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-populated-places/
    #           hreflang: en-US
    #         - type: application/gzip
    #           rel: canonical
    #           title: download
    #           href: http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_populated_places_simple.zip
    #           hreflang: en-US
    #     extents:
    #         spatial:
    #             bbox: [-38.245254, -11.568706, -36.399528, -9.520740]
    #             crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    #     providers:
    #         - type: feature
    #           name: Elasticsearch
    #           #Note elastic_search is the docker container of ES the name is defined in the docker-compose.yml
    #           data: http://elasticsearch:9200/sergipe-lito
    #           id_field: ogc_fid

